/* The different notes can be found in the link given below.
 * https://drive.google.com/file/d/1iKVL4MMMw9ur2h3HUDA-_qwnehT3Z2M1/view
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ishan;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author B.Bhoumick
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    
    private InputStream audio;
    
    public Piano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("checked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbCs = new javax.swing.JButton();
        jbC = new javax.swing.JButton();
        jbDs = new javax.swing.JButton();
        jbE = new javax.swing.JButton();
        jbD = new javax.swing.JButton();
        jbF = new javax.swing.JButton();
        jbB = new javax.swing.JButton();
        jbG = new javax.swing.JButton();
        jbA = new javax.swing.JButton();
        jbGs = new javax.swing.JButton();
        jbFs = new javax.swing.JButton();
        jbBb = new javax.swing.JButton();
        jbF1 = new javax.swing.JButton();
        jbE1 = new javax.swing.JButton();
        jbD1 = new javax.swing.JButton();
        jbC1 = new javax.swing.JButton();
        jbDs1 = new javax.swing.JButton();
        jbCs1 = new javax.swing.JButton();
        jcbMN = new javax.swing.JCheckBox();
        jcbSD = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Piano");

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIRTUAL PIANO");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jbCs.setBackground(new java.awt.Color(0, 0, 0));
        jbCs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCs.setForeground(new java.awt.Color(255, 255, 255));
        jbCs.setText("C#");
        jbCs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCsActionPerformed(evt);
            }
        });

        jbC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbC.setText(" C ");
        jbC.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCActionPerformed(evt);
            }
        });

        jbDs.setBackground(new java.awt.Color(0, 0, 0));
        jbDs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbDs.setForeground(new java.awt.Color(255, 255, 255));
        jbDs.setText("D#");
        jbDs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDsActionPerformed(evt);
            }
        });

        jbE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbE.setText(" E ");
        jbE.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEActionPerformed(evt);
            }
        });

        jbD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbD.setText(" D ");
        jbD.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDActionPerformed(evt);
            }
        });

        jbF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbF.setText(" F ");
        jbF.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFActionPerformed(evt);
            }
        });

        jbB.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbB.setText(" B ");
        jbB.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBActionPerformed(evt);
            }
        });

        jbG.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbG.setText(" G ");
        jbG.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGActionPerformed(evt);
            }
        });

        jbA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbA.setText(" A ");
        jbA.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAActionPerformed(evt);
            }
        });

        jbGs.setBackground(new java.awt.Color(0, 0, 0));
        jbGs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbGs.setForeground(new java.awt.Color(255, 255, 255));
        jbGs.setText("G#");
        jbGs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbGs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGsActionPerformed(evt);
            }
        });

        jbFs.setBackground(new java.awt.Color(0, 0, 0));
        jbFs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbFs.setForeground(new java.awt.Color(255, 255, 255));
        jbFs.setText("F#");
        jbFs.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbFs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFsActionPerformed(evt);
            }
        });

        jbBb.setBackground(new java.awt.Color(0, 0, 0));
        jbBb.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbBb.setForeground(new java.awt.Color(255, 255, 255));
        jbBb.setText("Bb");
        jbBb.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbBb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBbActionPerformed(evt);
            }
        });

        jbF1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbF1.setText("F1");
        jbF1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbF1ActionPerformed(evt);
            }
        });

        jbE1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbE1.setText("E1");
        jbE1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbE1ActionPerformed(evt);
            }
        });

        jbD1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbD1.setText("D1");
        jbD1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbD1ActionPerformed(evt);
            }
        });

        jbC1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbC1.setText("C1");
        jbC1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbC1ActionPerformed(evt);
            }
        });

        jbDs1.setBackground(new java.awt.Color(0, 0, 0));
        jbDs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbDs1.setForeground(new java.awt.Color(255, 255, 255));
        jbDs1.setText("D#1");
        jbDs1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbDs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDs1ActionPerformed(evt);
            }
        });

        jbCs1.setBackground(new java.awt.Color(0, 0, 0));
        jbCs1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbCs1.setForeground(new java.awt.Color(255, 255, 255));
        jbCs1.setText("C#1");
        jbCs1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jbCs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCs1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbC1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbF1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jbCs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDs)
                        .addGap(53, 53, 53)
                        .addComponent(jbFs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBb)
                        .addGap(58, 58, 58)
                        .addComponent(jbCs1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDs1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBb, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbCs1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDs1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbC, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbE, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbA, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbG, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbC1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbE1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbD1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbF1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jcbMN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbMN.setText("Music Notes");
        jcbMN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMNActionPerformed(evt);
            }
        });

        jcbSD.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbSD.setText("Steel Drum");
        jcbSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jcbMN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcbSD)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbMN)
                    .addComponent(jcbSD))
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCsActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C_s.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Cq_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCsActionPerformed

    private void jbDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDsActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D_s.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Dq_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDsActionPerformed

    private void jbGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\G.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\G_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbGActionPerformed

    private void jbGsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGsActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\G_s.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Gq_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbGsActionPerformed

    private void jbFsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFsActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\F_s.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Fq_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbFsActionPerformed

    private void jbBbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBbActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Bb.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Bb_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbBbActionPerformed

    private void jbD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbD1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbD1ActionPerformed

    private void jbDs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDs1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D_s1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Dq1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDs1ActionPerformed

    private void jbCs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCs1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C_s1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\Cq1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCs1ActionPerformed

    private void jbDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\D_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbDActionPerformed

    private void jbE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbE1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\E1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\E1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbE1ActionPerformed

    private void jbAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\A.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\A_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbAActionPerformed

    private void jbFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\F.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\F_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbFActionPerformed

    private void jbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCActionPerformed
        
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbCActionPerformed

    private void jcbMNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMNActionPerformed
        jcbSD.setSelected(false);
    }//GEN-LAST:event_jcbMNActionPerformed

    private void jcbSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSDActionPerformed
        jcbMN.setSelected(false);
    }//GEN-LAST:event_jcbSDActionPerformed

    private void jbEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\E.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\E_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbEActionPerformed

    private void jbBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\B.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\B_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbBActionPerformed

    private void jbC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbC1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\C1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbC1ActionPerformed

    private void jbF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbF1ActionPerformed
        if(jcbMN.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\F1.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        if(jcbSD.isSelected()){
            try{
                audio = new FileInputStream(new File("D:\\java workspace\\Music_Note\\F1_Drum.wav"));
                AudioStream music = new AudioStream(audio);
                AudioPlayer.player.start(music);
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jbF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Piano().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbA;
    private javax.swing.JButton jbB;
    private javax.swing.JButton jbBb;
    private javax.swing.JButton jbC;
    private javax.swing.JButton jbC1;
    private javax.swing.JButton jbCs;
    private javax.swing.JButton jbCs1;
    private javax.swing.JButton jbD;
    private javax.swing.JButton jbD1;
    private javax.swing.JButton jbDs;
    private javax.swing.JButton jbDs1;
    private javax.swing.JButton jbE;
    private javax.swing.JButton jbE1;
    private javax.swing.JButton jbF;
    private javax.swing.JButton jbF1;
    private javax.swing.JButton jbFs;
    private javax.swing.JButton jbG;
    private javax.swing.JButton jbGs;
    private javax.swing.JCheckBox jcbMN;
    private javax.swing.JCheckBox jcbSD;
    // End of variables declaration//GEN-END:variables
}
